version: "2"

services:
    web:
        build: .
        restart: always
        network_mode: "bridge"
        environment:
          - VIRTUAL_HOST=ly.yongbuzhixi.com
          - LETSENCRYPT_HOST=ly.yongbuzhixi.com
          - LETSENCRYPT_EMAIL=dale.tel@139.com